#!/usr/bin/env ruby

# ip-api check ip info command
# curl http://ip-api.com/json/24.48.0.1

require "net/http"
require "json"

if ARGV.length != 1 || ARGV[0].match(/-h|--help/)
  puts <<~EOS
    Usage:
        ip-api xxx.xxx.xxx.xxx(IP address)
  EOS
  exit(-1)
end

unless /^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.match?(ARGV[0])
  puts "Error: IP format error!"
  exit(-1)
end

uri = URI("http://ip-api.com/json/#{ARGV[0]}")
context = Net::HTTP.get(uri)

puts JSON.pretty_generate(JSON.parse(context))
